version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    container_name: my_redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
